### ISSUE TITLE
Add `DefaultRegion` to `aws-sso config` configuration wizard

### ISSUE THREAD

**Issue by ahollmann** [synfinatic/aws-sso-cli#1017]
Having the DefaultRegion set is pretty useful (not using the --advanced flag).

Having it set during the first start would improve the usability.

Thanks for your work on this tool.

**Comment by synfinatic** [comment]
it is useful, which is why it's in the advanced feature set, but it is definitely not required or appropriate for everyone, which is why it's not.  Thanks for the feedback though!  Glad to hear that feature and the tool overall is useful! :)
