### ISSUE TITLE
Windows WSL needs to default to `SecureStore: file`

### ISSUE THREAD

**Issue by Martin-Schlodinski** [synfinatic/aws-sso-cli#1023]
**Output of `aws-sso version`:**
```
Example output:
AWS SSO CLI Version 1.17.0 -- Copyright 2021-2024 Aaron Turner
8c32d5028c017fdfa9599756a7aea31b17f549a4 (v1.17.0) built at 2024-07-10T21:50:03+0000
```

**Describe the bug:**

When running any command like `aws-sso exec -p my_profile.dev` it shows error messages like these:

```
ERROR   unable to save RegisterClientData for Default  error="Object does not exist at path “/”"
...
ERROR   unable to save CreateTokenResponse            error="Object does not exist at path “/”"
```

The commands still work and I am able to log in but the login isn't cached. I have to go through 2FA every time again.

What I already tried:
- download latest version of aws-sso and aws cli
- removed `~/.aws`, `~/.aws-sso`, `~/.config/aws-sso`

**Expected behavior:**
The errors should not be shown and caching logins should work.

**Desktop (please complete the following information):**
 - Windows WSL, Ubuntu 24.04 LTS, kernel `5.15.153.1-microsoft-standard-WSL2`

**Additional context:**
`strace` output says "operation not permitted" for `~/.aws-sso/config`/`cache` and many certificates although :

```
openat(AT_FDCWD, "/home/martin/.aws-sso/config.yaml", O_RDONLY|O_CLOEXEC) = 7
fcntl(7, F_GETFL)                       = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fcntl(7, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 7, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=2971140097, u64=9167057287634223105}}) = -1 EPERM (Operation not permitted)
fcntl(7, F_GETFL)                       = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
fcntl(7, F_SETFL, O_RDONLY|O_LARGEFILE) = 0
fstat(7, {st_mode=S_IFREG|0755, st_size=276, ...}) = 0
read(7, "SSOConfig:\n    Default:\n        "..., 512) = 276
read(7, "", 236)                        = 0
close(7)                                = 0
openat(AT_FDCWD, "/home/martin/.aws-sso/cache.json", O_RDONLY|O_CLOEXEC) = 7
fcntl(7, F_GETFL)                       = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fcntl(7, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 7, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=2971140098, u64=9167057287634223106}}) = -1 EPERM (Operation not permitted)
fcntl(7, F_GETFL)                       = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
fcntl(7, F_SETFL, O_RDONLY|O_LARGEFILE) = 0
fstat(7, {st_mode=S_IFREG|0755, st_size=18296, ...}) = 0
read(7, "{\n  \"Version\": 4,\n  \"ConfigCreat"..., 18297) = 18296
read(7, "", 1)                          = 0
close(7)                                = 0
openat(AT_FDCWD, "/home/martin/.aws-sso/cache.json", O_RDONLY|O_CLOEXEC) = 7
fcntl(7, F_GETFL)                       = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fcntl(7, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 7, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=2971140099, u64=9167057287634223107}}) = -1 EPERM (Operation not permitted)



...


openat(AT_FDCWD, "/etc/ssl/certs/ISRG_Root_X2.pem", O_RDONLY|O_CLOEXEC) = 8
fcntl(8, F_GETFL)                       = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fcntl(8, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=2308440158, u64=9179378985503031390}}) = -1 EPERM (Operation not permitted)
```

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    Default:
        SSORegion: eu-central-1
        StartUrl: https://[REDACTED].awsapps.com/start
ConsoleDuration: 720
CacheRefresh: 168
UrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ .AccountAlias }}"
FullTextSearch: true
```

I appreciate any help! :) Thank you!

**Comment by synfinatic** [comment]
the "operation not permitted" is a red herring.  The real issue is the two ERROR messages.  

My windows computer is in a box in the garage right now, so not easy for me to reproduce, but what happens if you set `SecureStore: file` in the config.yaml?

**Comment by Martin-Schlodinski** [comment]
oh wow that indeed helped: it asks me to select a password and I could then successfully log in *without* the error message. Also caching the login works well now! It asks me to enter the password for to unlock `/home/martin/.aws-sso/secure` as it should.
Thank you so much for the quick help!

**Comment by synfinatic** [comment]
Fix OS detection on WSL so that it doesn't try to use the Windows Credential Store which is not available under Linux.

**Comment by synfinatic** [comment]
@Martin-Schlodinski : So I tried to reproduce this issue on Win10/WSL/Ubuntu 22.04 and other than the version of Linux (I just used the default install), I believe this to be the same as yours?  Long story short, I was not able to reproduce this issue.  `aws-sso` correctly identified this as Linux and used the default `SecureStore: file` backend without having to be told explicitly to do so.

I was assuming up until this time, `aws-sso` was mischaracterizing the system as Windows and was trying to use the Windows Credential Manager which would not be accessible from under Linux/WSL.

Honestly, I'm not at all a Windows person (I resurrected an old mini-PC and installed a fresh copy of  Win10  on it) and so perhaps there are more than one way of executing things under WSL which might explain why you and I are having different results?  I was hoping you might be able to provide more information so that I could reproduce your issue.

**Comment by synfinatic** [comment]
ping @Martin-Schlodinski .  would love to get more info from you or I'll need to close this ticket.

**Comment by Martin-Schlodinski** [comment]
oh wow thank you @synfinatic for looking into it! When I posted this issue I was using Ubuntu 24.04 and in the meantime switched to 22.04 where it works flawless. I now reinstalled 24.04 to reproduce the issue but I'm failing to do so... I assume we can indeed close this issue then. Thank you for the effort though!!
