### ISSUE TITLE
Change the "Expires" to something greater than 60 minutes

### ISSUE THREAD

**Issue by 3uzbcqje** [synfinatic/aws-sso-cli#1060]
**Is your feature request related to a problem? Please describe.**
I am frustrated that I have to run aws-sso-profile at least 8 times during a regular workday, because the sessions expire in 60 minutes. I am constantly running kubectl commands or k9s and having them fail, then having to re-run aws-sso-profile to refresh my session.

**Describe the solution you'd like**
Is there a way to set the expiration to once every 8, 12, or 24 hours?

**Describe alternatives you've considered**
My solution is this goofy script I wrote: https://gitlab.com/devopscoop/scripts/-/blob/main/aws_configure_all_sso.sh?ref_type=heads
...but I would prefer to use aws-sso-cli because of the enhanced security.

**Additional context**
Perhaps it's an anti-pattern from a security perspective to increase the session expiration above 60 minutes, but it's so annoying that I've fallen back to using the standard AWS CLI (via the script above). However, I still think encryption + 8 hour expiration is better security than no encryption and whatever magic AWS CLI uses to avoid the 60 minute expiration.

**Comment by synfinatic** [comment]
Hi @evanstucker-hates-2fa,

This is not something that `aws-sso` controls, but rather the administrator of AWS Identity Center.  Assuming you are the admin, you can navigate in the AWS Console to: IAM Identity Center -> Permission Sets and then select the permission set you wish to increase the session time.  Click Edit and then change the Session duration to the desired value.

more info: https://docs.aws.amazon.com/singlesignon/latest/userguide/howtosessionduration.html

**Comment by synfinatic** [comment]
There's really no great portable way to do this right now.  In the future, I kinda hope the ecs server running in docker can deal with this sorta use case, but it's gonna be a long way before that happens.  In all honestly, your best bet is to talk to your admin and ask them to increase the default 1hr value and why it's a problem.  Most of the time, they just accepted the defaults without thinking.

**Comment by synfinatic** [comment]
Oh, if you want to use the `AWS_PROFILE` environment variable then the [config-profiles](https://synfinatic.github.io/aws-sso-cli/v1.17.0/commands/#config-profiles) command will do what you want by generating the appropriate entries in your `~/.aws/config` file.

What I can't do easily is modify your current shell's environment.

**Comment by synfinatic** [comment]
I'm not really sure why you're running `aws-sso-profile xxxx` at all.  Just should need `export AWS_PROFILE=xxx`.  Is there a problem if you don't?
