### ISSUE TITLE
Devcontainer feature

### ISSUE THREAD

**Issue by kevcube** [synfinatic/aws-sso-cli#1071]
**Is your feature request related to a problem? Please describe.**
We are using `aws-sso-cli` in codespaces and it would be great to have a `devcontainer` feature with configuration options for all the options that go into `aws-sso/config.yaml`

**Describe the solution you'd like**
https://github.com/microsoft/dev-container-features-template example repo

A devcontainer feature with configuration options for `aws-sso/config.yaml`, such as SSO Start URL, URL action, and others.

**Comment by synfinatic** [comment]
Trying to wrap my head around this request... you're not looking to do `aws-sso` development in a devcontainer, but rather use `aws-sso` inside of a remote devcontainer?     I notice you're not asking for the ability to select an IAM role to assume in this ticket which has me confused what the desired result is.

**Comment by kevcube** [comment]
Correct, I want to be able to install `aws-sso-cli` in a devcontainer using [devcontainer features](https://containers.dev/features). And I also want to be able to define configuration for the `aws-sso/config.yaml` file at some point where users can share this configuration on an org-wide level.

I am hopeful that this second part can be done through devcontainer feature configuration, but it may not be possible at that level. So I'm also looking at sharing a `dotfiles` repo for org-wide codespaces.

**Comment by synfinatic** [comment]
are you running the devcontainer locally or in the cloud?

**Comment by kevcube** [comment]
in github codespaces

**Comment by synfinatic** [comment]
you do realize of course, that doing this means your dev environment, running in github would have access to ALL your IAM roles? So for example if you're read-only in one account and admin in another account, anyone at github with root access to the underlying system would be able to assume any role you have access to.  It's a huge security risk.

What it seems like is what you really want to do is be able to select a specific IAM role credentials to be injected into the container?

**Comment by kevcube** [comment]
This is for a client where we already place great trust in GitHub, and are switching developer workflows to be inside of codespaces, so the issue of trust is not one of our main concerns, but still worth considering. Also, we are using encrypted file as our “keychain”, so without snooping on our sessions GitHub wouldn’t necessarily have the ability to use our roles, right?

And about injecting a specific role into the container – I don’t know of any way that’s possible today because these codespaces would usually be launched by client’s devs through the web ui. Even if they were using CLI tools I still don’t see how it’s possible within reasonable effort (no ssh, etc)

**Comment by kevcube** [comment]
If we wanted to inject just one role, we could just copy and paste creds from the aws sso landing page, but we DO want aws sso cli access to multiple accounts from within codespaces. I don’t believe their engineers have admin access to our higher accounts but this is an RBAC concern I’ll raise internally. In the end I think we’ll say “we trust GitHub/codespaces”

**Comment by synfinatic** [comment]
in all seriousness, isn't this what github secrets are for?  just put the role credentials in the ENV of the project?

In all honesty, this is a super niche request and not something AFAICT that actually needs to be supported by `aws-sso` natively.  Basically, nothing prevents you from creating your own devcontainer with whatever options/features you need and generating the `~/.aws-sso/config.yaml` as far as I can tell.  I don't see any point in supporting this feature as I do not believe it is relevant for 99% of users and frankly isn't a feature I would personally recommend.

That said, if there is some feature that needs to be implement in the aws-sso _binary_ to enable this workflow, I'm open to discussing.

**Comment by kevcube** [comment]
I think we _might_ be missing each other’s points here.

I’m just asking for a feature that will install aws-sso inside of devcontainers generically. The configuration options are beyond that, and can be done with dotfiles. People won’t be sharing actual access credentials.

Codespaces secrets doesn’t help to solve AWS SSO in any way that I can see without users having to update their secrets once every 24h.

if I’m wrong and you got that then leave this issue closed otherwise reopen and it might be something I can find time to work on. I was able to use aws sso from a package manager (aqua) and install it to a devcontainer so this is no longer a blocker of anything for me

**Comment by synfinatic** [comment]
My understanding is you're basically asking me to create a JSON file and shell script to make it easier to use `aws-sso` with a devcontainer.  I'm saying there is nothing stopping you from doing that and that I don't want to maintain those files.

If there is functionality `aws-sso` binary needs to enable you to be successful, I'm open to seeing what can be done.
