### ISSUE TITLE
How to manage Keychain

### ISSUE THREAD

**Issue by channyein87** [synfinatic/aws-sso-cli#156]
Is it possible to change the password given to Keychain during the initial setup or may be if there is a way to delete the existing Keychain record and recreate with new password?

**Comment by synfinatic** [comment]
There is no way to do this from aws-sso itself, but you can use the macOS Keychain Access tool to do that.  

`File -> Add Keychain` and then select `AWSSSOCli`  then `Edit -> Change pasword for AWSSSOCli`

Or you can just delete the keychain file itself from `~/Library/Keychains/` and let aws-sso recreate it and prompt you for a new one.

**Comment by synfinatic** [comment]
added to the FAQ
