### ISSUE TITLE
More example for templating profile name

### ISSUE THREAD

**Issue by rgarrigue** [synfinatic/aws-sso-cli#244]
Hi there

My roles in AWS are named casually, hence `aws-sso config` end up with stuff like `[profile Data DEV:Admin]`. I wanted to apply a simple to lower case + replace white space by _ ... But I couldn't. 

I'm not a go dev, so far I understood that go/text offer a very limited number of functions and you've to extend this yourself. Have you done it ? Because I found programmatical way like [this](https://go.dev/play/p/z-yyM6mVt8), but I'm not writing a .go. Since I'm after compilation time I doubt I can do heavy inline stuff like those anyway. 

So, have you any additional functions you could document ? If you don't have any, you could consider adding a library like [sprig](https://github.com/Masterminds/sprig), seems fairly easy ?

**Comment by synfinatic** [comment]
There's no way to lower/upper case a string today (but that is a good idea! and I'll add it), but there is a way to replace spaces with underscore as shown in the FAQ: https://github.com/synfinatic/aws-sso-cli/blob/main/docs/FAQ.md#how-to-configure-profileformat
