### ISSUE TITLE
Investigate SAML support

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/aws-sso-cli#275]
I have code for SAML with OneLogin, but no idea if this code is useful for Okta and other SAML providers.  What do the other SAML SSO provider API's look like?  Can I use the same code or is each vendor a special snowflake? Anyways, lots of older SAML integrations out there.  But would also require me to spin up a devel instance and get some kind of developer account from the SAML vendor(s)?  

I don't believe there is a way to auto-discover AWS roles via SAML integration. 

 * OneLogin: https://developers.onelogin.com/openid-connect/api/authorization-code
 * Okta: https://developer.okta.com/docs/guides/implement-grant-type/authcode/main/

Both have Go SDK's (neither looks particularly good!)
 * https://github.com/okta/okta-sdk-golang
 * https://github.com/onelogin/onelogin-go-sdk

Both have free developer accounts:
 * https://developer.okta.com/signup/
 * https://www.onelogin.com/developer-signup

**Comment by sama8** [comment]
If relevant -> [SAML Jackson](https://github.com/boxyhq/jackson)

**Comment by synfinatic** [comment]
Lack of role discovery seems to be a big problem here and an opportunity for providing value if I can provide a better UX than the current.

Challenge is of course that the SAML workflows don't really fit with AWS SSO and not sure if having a unified tool really makes sense unless there is a lot of common functionality I can leverage.

**Comment by eggplants** [comment]
The following information may be helpful regarding the implementation of SAML login using IAM Identity Center Application:
- https://github.com/Versent/saml2aws
- https://aws.amazon.com/jp/blogs/security/how-to-implement-a-general-solution-for-federated-apicli-access-using-saml-2-0/

As you know, AWS does not provide a simple mechanism for receiving callbacks after performing external authentication from a web page, so it’s quite a hassle because you have to use a headless browser, such as `saml2aws`.

Ref: https://github.com/aws/aws-cli/issues/9641

**Comment by synfinatic** [comment]
@eggplants is this something you actually need?  As you can see, this ticket was closed as not planned nearly 3 years ago.

**Comment by eggplants** [comment]
Since this feature isn't available in `aws sso` for now, it would be great to see it in a third-party tool like your `aws-sso`.

**Comment by synfinatic** [comment]
@eggplants  Yeah, `aws sso` doesn't support it because AWS understands that SAML sucks and doesn't want to encourage using it.  The whole web scraping thing is just asking for things to randomly break.  If you really want this feature you're going to have to provide a lot more of a justification than "it would be nice". :) 

Honestly though I'm going to need a lot more people asking for this than what is currently expressed in this ticket for me to consider it.
