### ISSUE TITLE
Track down reading $HOME/.aws/credentials

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/aws-sso-cli#280]
Shouldn't be doing this?  See https://github.com/synfinatic/aws-sso-cli/issues/279#issuecomment-1029044796

**Comment by mouchar** [comment]
I don't believe this is a security issue, it's most probably regular behavior of the aws-sdk-go client.
But better be safe than sorry ;)

**Comment by synfinatic** [comment]
Agreed.  Mostly, I'd rather not open files with secrets if I don't need to.  Rather not have them in my process memory where bad things could happen.
