### ISSUE TITLE
For automation needs, have a similar UrlAction `print` but only printing the url on stdout - without any pre / post text

### ISSUE THREAD

**Issue by llange** [synfinatic/aws-sso-cli#303]
**Is your feature request related to a problem? Please describe.**
It's a minor annoyance, I have a workaround.  
I'd like to automate the opening of some AWS console sessions in tabs (containers), so that those sessions are isolated in the browser.
I'm using this extension https://github.com/honsiorovskyi/open-url-in-container which provides the ability to launch an URL in a specific container tab (and a cli launcher).
However the [current implementation](https://github.com/synfinatic/aws-sso-cli/blob/main/utils/utils.go#L75-L76) of the `print` UrlAction of `aws-sso` has 2 "issues":
* It outputs to `stderr`
* It prints some text before and after the url ("Please open the following URL in your browser:").
 
thus I need to post-process the (`stderr`) output of `aws-sso console` to extract the url.
(And I cannot use the `--browser` argument as it's not intended to have parameters).

I thought it could be nice to have a full non-interactive output for automation.
I like the idea of each tool doing its own job, and chaining the output / result of the tools to compose a solution (Instead of having too much features in a tool).

**Describe the solution you'd like**
- Either an additional option `--url-action=XXXXX`, or a decision to remove all the accompanying text when using `--url-action=print` (which may be inconvenient to existing users)
- All useful data should go to `stdout`
(May be a solution could be to print the accompanying text to `stderr`, while the data itself is output to `stdout` ; there may be a risk in display order).

**Describe alternatives you've considered**
Currently I'm post-processing `stderr` to extract the URL:
```
aws-sso console --arn arn:aws:iam::XXXXXXXXXXXXX:role/YYYYYYYYYYYY --url-action=print 2>&1 | sed -ne 's/\(http[^"]*\).*/\1/p' | xargs firefox-launcher (args) (args)
```
which works great.

**Comment by synfinatic** [comment]
so the `--url-action=print` command can't print anything to `stderr` because that will interfere with things like `eval $(aws-sso eval ...)` to load the AWS creds into the existing shell environment.

That said, I can create a new `--url-action` which only prints the url without the accompanying text for easier integration (remove the `sed`), but I think it should still go to stderr because of the above.

Is that a reasonable compromise?

**Comment by llange** [comment]
Hi,
thanks for the answer ; and yes, it does sound like an interesting addition, thanks !!
Let me know how I can help on this.

**Comment by synfinatic** [comment]
@llange: just a follow up, if you get a chance, check out the new `exec` feature I added.  I think that should be an even better solution to the `printurl` option we discussed.  LMK if you have any questions.
