### ISSUE TITLE
Quickstart documentation has deadlink and alias that does not work

### ISSUE THREAD

**Issue by pmastela** [synfinatic/aws-sso-cli#368]
**Describe the bug:**
Link in quickstart is a dead link

**To Reproduce:**
 1. Visit https://github.com/synfinatic/aws-sso-cli/blob/main/docs/quickstart.md#aws-sso-profile-helper-script
 2. Click [scripts directory](https://github.com/synfinatic/aws-sso-cli/blob/main/scripts).
 3. 404

**Expected behavior:**
Linked page exists

**Describe the bug:**
Link in quickstart is a dead link

**To Reproduce:**
 1. Follow quickstart, and set `alias aws-sso-profile='source /usr/bin/helper-aws-sso-profile'`
 2. Reload shell
 3. run `aws-sso-profile`
 4. see `source: no such file or directory: /usr/bin/helper-aws-sso-profile`

**Expected behavior:**
Alias works

**Additional context:**
- I'm guessing all this has to do with the [massive updates to scripts commit](https://github.com/synfinatic/aws-sso-cli/commit/fdba444a2a6f7b99e8de68bfdadb28a669394fcf)

**Comment by synfinatic** [comment]
Thanks for the report!
