### ISSUE TITLE
Support ECS server endpoint

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/aws-sso-cli#398]
This is different from the standard metadata service #265 because it runs on an ephemeral port and depends on the SDK supporting `AWS_CONTAINER_CREDENTIALS_FULL_URI`

More info how this works here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html

**Comment by synfinatic** [comment]
@wparad since you voted for this feature, I'm curious if your use case would require `aws-sso` to run in the background as a service/deamon or is something in the foreground (appropriate for a docker container) more along what you were thinking?

**Comment by wparad** [comment]
I'm not totally sure I understand what the difference would be. Is there one that is easier? That we could test out and if works great! and if not we could create follow up issue?
