### ISSUE TITLE
Official darwin/arm64 release does not work with macOs Keychain

### ISSUE THREAD

**Issue by andreadelfino** [synfinatic/aws-sso-cli#407]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.9.2 -- Copyright 2021-2022 Aaron Turner
307f13eb377284001a3545ea1394c2303786925f (v1.9.2) built at 2022-05-13T17:07:59-0700
```
(also checked 1.9.* and 1.8.* binaries)

**Describe the bug:**
The official binary release of `aws-sso` for darwin/arm64 uses `file` as default secure store if none is specified.

When `SecureStore: keychain` is specified I get the following error:
```
FATAL   Unable to open SecureStore keychain           error="Specified keyring backend not available"
````

**To Reproduce:**
The store seems to be checked very early in the execution flow so even basic command like `aws-sso version` can be used to reproduce it.

**Expected behavior:**
Be prompted for Keychain password as default behaviour.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 12.4
 - Arch: arm64 (M1)

**Additional context:**
Comparing the binaries it seems that `github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4` vendor (99designs/keyring dependency) is not present in arm64 build. I checked Darwin release for amd64 and those works as expected and the the vendor lib is there.

Building the project from source with a simple `make` produces a fully working binary (on my machine :)

**Comment by synfinatic** [comment]
yes, there seems to be an issue with the keychain library when cross-compiling it seems.  hence installing via source or `brew` seems like the best way.  

Since I don't have a M1 Mac and can't test locally- any chance you're willing to be a guinea pig and test for me?

**Comment by synfinatic** [comment]
try this? [aws-sso-1.9.3-darwin-arm64.zip](https://github.com/synfinatic/aws-sso-cli/files/9078112/aws-sso-1.9.3-darwin-arm64.zip)

**Comment by synfinatic** [comment]
ping: @andreadelfino

**Comment by andreadelfino** [comment]
Hi, sorry for the delay, I had the chance to test it today and the integrations with macOs Keychain works flawlessly! Huge thanks!

**Comment by synfinatic** [comment]
Ah, glad to hear it!
