### ISSUE TITLE
Entering SSO Start URL Hostname in wizard is unintuitive

### ISSUE THREAD

**Issue by altosys** [synfinatic/aws-sso-cli#416]
**Is your feature request related to a problem? Please describe.**
The way the user is requested to enter the `SSO Start URL Hostname` in the configuration wizard is confusing and incorrect.

The user is prompted by the below, the way that this request is displayed with the `.awsapps.com` inside the parenthesis makes the user expect to enter the whole URL, such as `d-123456789.awsapps.com`, and not just the alphanumeric identifier. The parameter also specifically asks for the `Hostname`, to which responding with just `d-123456798` is not really correct. 

```
✔ SSO Start URL Hostname (XXXXXXX.awsapps.com):
```

Entering the hostname as input fails with a duplicate of the parent domain in the URL:
```
✔ SSO Start URL Hostname (XXXXXXX.awsapps.com): d-123456789.awsapps.com|
ERROR   Unable to resolve d-123456789.awsapps.com.awsapps.com
```

**Describe the solution you'd like**
The wizard should be updated to accept the actual hostname in addition to just the identifier, this is just trivial string handling, but at least it would accept correct input based on what the prompt is requesting and not stop a new user from getting needless errors when setting up the tool for the first time.

**Comment by synfinatic** [comment]
Seems like there is a confusion between the "hostname" and "fully qualified domain name" (FQDN).  The hostname is `d-12345678`, the FQDN is `d-12345678.awsapps.com`.   This is why if you type in `d-12345678` things work correctly because the `awsappps.com` part is fixed.

But yeah, the prompt should accept either.
