### ISSUE TITLE
Regression ? "role chain loop detection" seems to trigger without any Role defined / without any `Via:`

### ISSUE THREAD

**Issue by llange** [synfinatic/aws-sso-cli#425]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.9.3 -- Copyright 2021-2022 Aaron Turner
cc2815db354c12f7e915c2255ab6ca2bff643104 (Homebrew) built at 2022-09-29T06:16:42+0000
```

**Describe the bug:**
I'm not using the role-chaining feature (`Via:` keyword) described in [the documentation](https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md#via).

Since this version 1.9.3, I cannot use aws-sso any more, it triggers the following error:
```
FATAL   Detected role chain loop!  Getting  via
```
In `TRACE` mode:
```
level=fatal msg="Detected role chain loop!  Getting  via "
```

which seems to come from #203 .

**To Reproduce:**
Juste try to open a console with any profile:
```
$ aws-sso console --profile="XXXXXXXXXXX:zzzzzzzzzzzz:tttttttttttttttt"
FATAL   Detected role chain loop!  Getting  via    
```

**Expected behavior:**
web console should open as before.

Reverting to [version 1.9.2](https://github.com/synfinatic/aws-sso-cli/releases/tag/v1.9.2) fixes the issue.

**Screenshots:**
N/A

**Desktop (please complete the following information):**
```
      System Version: macOS 11.6.5 (20G527)
      Kernel Version: Darwin 20.6.0
root:xnu-7195.141.26~1/RELEASE_X86_64
```

**Additional context:**

**Contents of `~/.aws-sso/config.yaml`:**
No role is defined in the configuration - only the accounts:
```
...
    Accounts:
      '000000000000':
        Tags:
          Prod: true
          Color: red
          Icon: briefcase
        Name: Account1
...
```

**Comment by rzamana** [comment]
Having the same, since I updated!

**Comment by synfinatic** [comment]
Ouch.  thanks for the report!
