### ISSUE TITLE
Transparent building of binary files

### ISSUE THREAD

**Issue by DainiusSal** [synfinatic/aws-sso-cli#432]
**Problem**
Right now it is possible to either clone the repository and run build scripts yourself or download the binary files. Cloning and running build scripts manually takes time and it could become cumbersome to do so with every release. Downloading binary files [from the repository](https://github.com/synfinatic/aws-sso-cli/releases) is very convenient, however, the build process is not transparent, thus, from security standpoint, it is not a very attractive solution- binary files could be tampered with.

**Solution**
Create GitHub Actions workflow for automated building of the binary files.

**What I've explored**
I checked the GitHub Actions workflows and could not find a workflow for building the binary files.

**Comment by synfinatic** [comment]
I'm curious why using `brew` or `go install` [per the docs](https://github.com/synfinatic/aws-sso-cli/blob/main/docs/quickstart.md#installation) is considered too cumbersome?

I get that it takes more time to build yourself, but that in the light of the Solarwinds attack would be considered more trustworthy right?

**Comment by DainiusSal** [comment]
The reason why it is too cumbersome is because I would be using it on multiple machines which will have different architectures, different OS. With each new release, I will need to re-build it manually on all of those machines which would be much easier if the process was automated.

That's true, in case of Solarwinds attack, it would be more secure to build it manually but, in general, it would still be more trustworthy to download binaries from an automated build than from black box build.

**Comment by DainiusSal** [comment]
Opened a PR which implements automated building: https://github.com/synfinatic/aws-sso-cli/pull/433
