### ISSUE TITLE
Option to list History first in interactive menu

### ISSUE THREAD

**Issue by drboyer** [synfinatic/aws-sso-cli#445]
**Is your feature request related to a problem? Please describe.**
There's some occasions when I might want to use `aws-sso exec` to execute commands in different AWS accounts or with different roles, but they are roles that I have used recently, and would show up in the `History` list. If you are interactively choosing a role with aws-sso, you can get to History by typing `h` (at minimum) or hitting the Down Arrow 4 times. Out of force of habit, I find myself frequently using the arrow keys instead of filtering the list by keyword.

**Describe the solution you'd like**
As such, it might be cool if there was an option that would force `History` to show up first in the interactive menu, above AccountAlias, AccountId and the like. I imagine there are other users who work frequently with the History list and would like another way to access it easier.

In slightly further detail, I imagine adding a new setting to the config.yaml like `ShowHistoryFirst: true`, which when set, would then result in a prompt like this:

```
$ aws-sso exec
Please use `exit` or `Ctrl-D` to quit.
>
   History       3 roles/3 choices
   AccountAlias  10 roles/3 choices
   AccountID     10 roles/3 choices
   Email         10 roles/3 choices
   Role          10 roles/4 choices
```

...instead of the usual order. I'm fine leaving the alphabetical order the default. Maybe I'm special with my preference for the arrow keys? 🤣 

**Describe alternatives you've considered**
not sure there are particular alternative to this, it's either a good idea or an unnecessary feature. Figured best to open a ticket for any discussion first.

**Additional context**
If you think this is a worthwhile idea but don't have capacity to build it, I'm happy to try and put together a PR to implement it.

**Comment by synfinatic** [comment]
I'm glad you figured out you can start typing the name of the tag, but I get the arrow key being more intuitive for some.

I can imagine different people wishing different tags (or History) to have different priorities.  Rather than a "PutHistoryOnTop = true" what about a "TagOrder" which is a list?

**Comment by drboyer** [comment]
Sure that seems reasonable also. Are there only ever those 5 tags available?

**Comment by synfinatic** [comment]
@drboyer looking back at this... are you on Windows perhaps?  Arrow keys are working for me.
