### ISSUE TITLE
Notify user by default when refreshing cache - large account lists specific issue

### ISSUE THREAD

**Issue by colatricks** [synfinatic/aws-sso-cli#448]
Hi,

Firstly thank you for developing this, such a neat tool! Can I make a small suggestion that when the app is refreshing it's cache, that the user is informed by default? 

When I initially installed it and ran `aws-sso list` I thought it was broken, but after redoing the config setup and changing the error level to debug I realised it was just taking a long time to return the cache content. 

For context we have in excess of 800 AWS accounts - the cache creation takes 7 and a half minutes. 

https://github.com/synfinatic/aws-sso-cli/blob/bb21328628642e0b95166289527adacf0a2740d9/cmd/aws-sso/main.go#L331

**Comment by synfinatic** [comment]
Wow, 800 accounts!  That's probably more than most organizations.  I try to keep aws-sso quiet by default because my experience is that when there is too much output (more than a couple of lines) people won't read it at all when there are errors and immediately throw up their hands.

However, appearing to hang is also a bad UX.  Maybe I can come up with something in the middle that works well for everyone.

**Comment by colatricks** [comment]
Yep! We utilize accounts as a segregation point for our customers data - although I suspect with the recent ability being released for accounts to be spun up (and down) by CloudFormation folk will generally start to grow their accounts list over time. Appreciate you taking the time to take a look - I know it's a niche scenario!

**Comment by synfinatic** [comment]
The above PR should do two things:
 1. If updating the cache is taking > 2sec, let you know we're working on it
 2. Improve performance by using goroutines to pull the data from AWS in parallel.  Default is currently 10.

Since your environment is pretty close to a "worst scenario" I'd appreciate it if you could test the above PR and make sure it's reliable for you.  I'm not sure the default of 10 "Threads" (see the docs) is safe or not?  If not, what is safe?

**Comment by colatricks** [comment]
@synfinatic kind of a success? Cache refresh time got down to 1m 42s which is a good improvement! Some unusual behaviour .. just detailing the step by steps from my side (incase I'm doing something wrong): 

```
git clone https://github.com/synfinatic/aws-sso-cli.git
git fetch --all
gh pr checkout 449
make
cd dist
./aws-sso
```

On the first run, I ended up with (it goes on for quite a bit longer than this but they all seem to be the same sort of output: 

```
 ~/Co/w/aws-sso-cli/dist cache-refresh ./aws-sso                                                                     
fatal error: concurrent map writes

goroutine 873 [running]:
github.com/synfinatic/aws-sso-cli/sso.(*AWSSSO).makeRoleInfo(0x14000430000, {0x121, {0x140000b63a0, 0xc}, {0x140000b63c0, 0x9}, {0x140001c85e0, 0x1e}}, 0x0, {0x140003fe560?, ...})
	/Users/johnathan/Code/work/aws-sso-cli/sso/awssso.go:195 +0x1dc
github.com/synfinatic/aws-sso-cli/sso.(*AWSSSO).GetRoles(0x14000430000, {0x121, {0x140000b63a0, 0xc}, {0x140000b63c0, 0x9}, {0x140001c85e0, 0x1e}})
	/Users/johnathan/Code/work/aws-sso-cli/sso/awssso.go:164 +0x63c
github.com/synfinatic/aws-sso-cli/sso.fetchSSORole(0x0?, 0x104b4cfd4?, 0x14000436300?, 0x0?)
	/Users/johnathan/Code/work/aws-sso-cli/sso/cache.go:432 +0x130
created by github.com/synfinatic/aws-sso-cli/sso.(*Cache).addSSORoles
	/Users/johnathan/Code/work/aws-sso-cli/sso/cache.go:516 +0x3fc

goroutine 1 [select]:
github.com/synfinatic/aws-sso-cli/sso.(*Cache).addSSORoles(0x14000033500, 0x104af4e3c?, 0x14000430000)
	/Users/johnathan/Code/work/aws-sso-cli/sso/cache.go:523 +0x500
github.com/synfinatic/aws-sso-cli/sso.(*Cache).NewRoles(0x14000033500, 0x140001d1f50?, 0x14000226ff0)
	/Users/johnathan/Code/work/aws-sso-cli/sso/cache.go:408 +0xf4
github.com/synfinatic/aws-sso-cli/sso.(*Cache).Refresh(0x14000033500, 0x9?, 0x14000226ff0, {0x1400033e2a0, 0x9})
	/Users/johnathan/Code/work/aws-sso-cli/sso/cache.go:307 +0x394
main.doAuth(0x140001d1590)
	/Users/johnathan/Code/work/aws-sso-cli/cmd/aws-sso/main.go:336 +0x230
main.(*CacheCmd).Run(0x14000033500?, 0x140001d1590)
	/Users/johnathan/Code/work/aws-sso-cli/cmd/aws-sso/cache_cmd.go:28 +0x24
main.(*DefaultCmd).Run(0x1?, 0x140001d1590)
	/Users/johnathan/Code/work/aws-sso-cli/cmd/aws-sso/list_cmd.go:100 +0x58
reflect.Value.call({0x10514dba0?, 0x140001118f0?, 0x14000225a48?}, {0x104fe34f6, 0x4}, {0x140004023a8, 0x1, 0x104cd100c?})
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/reflect/value.go:584 +0x688
reflect.Value.Call({0x10514dba0?, 0x140001118f0?, 0x5a88?}, {0x140004023a8?, 0x1057205b8?, 0x10?})
	/opt/homebrew/Cellar/go/1.19.3/libexec/src/reflect/value.go:368 +0x90
github.com/alecthomas/kong.callMethod({0x104fe305e, 0x3}, {0x10515ebe0?, 0x140001118f0?, 0x3?}, {0x10514dba0?, 0x140001118f0?, 0x1?}, 0x0?)
	/Users/johnathan/go/pkg/mod/github.com/alecthomas/kong@v0.2.18/callbacks.go:97 +0x3f0
github.com/alecthomas/kong.(*Context).RunNode(0x140000dac80, 0x140001a62a0, {0x14000225ec8, 0x1, 0x1})
	/Users/johnathan/go/pkg/mod/github.com/alecthomas/kong@v0.2.18/context.go:731 +0x460
github.com/alecthomas/kong.(*Context).Run(0x140003ae000?, {0x14000225ec8?, 0x104fe6c1b?, 0x24?})
	/Users/johnathan/go/pkg/mod/github.com/alecthomas/kong@v0.2.18/context.go:756 +0x144
main.main()
	/Users/johnathan/Code/work/aws-sso-cli/cmd/aws-sso/main.go:191 +0x86c

goroutine 878 [runnable]:
github.com/aws/aws-sdk-go-v2/aws/retry.NewAttemptMiddleware({0x1051ff040, 0x140000f2420}, 0x1051f62f8, {0x1400030b3b0, 0x1, 0x1?})
	/Users/johnathan/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.16.2/aws/retry/middleware.go:44 +0x90
github.com/aws/aws-sdk-go-v2/aws/retry.AddRetryMiddlewares(0x1400027e2c0, {{0x1051ff040?, 0x140000f2420?}, 0xc0?})
	/Users/johnathan/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.16.2/aws/retry/middleware.go:320 +0x74
github.com/aws/aws-sdk-go-v2/service/sso.addRetryMiddlewares(_, {{0x1055ada78, 0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {{0x0, ...}, ...}, ...})
	/Users/johnathan/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/sso@v1.9.0/api_client.go:327 +0x34
github.com/aws/aws-sdk-go-v2/service/sso.(*Client).addOperationListAccountRolesMiddlewares(_, _, {{0x1055ada78, 0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
	/Users/johnathan/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/sso@v1.9.0/api_op_ListAccountRoles.go:91 +0x194
github.com/aws/aws-sdk-go-v2/service/sso.(*Client).invokeOperation(0x140000e0500, {0x1051fe650?, 0x140000b6010?}, {0x104fe988a, 0x10}, {0x10514ac00, 0x140003eb950}, {0x0, 0x0, 0xbc6fa42e4d914378?}, ...)
	/Users/johnathan/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/sso@v1.9.0/api_client.go:159 +0x2dc
github.com/aws/aws-sdk-go-v2/service/sso.(*Client).ListAccountRoles(0x105158220?, {0x1051fe650?, 0x140000b6010?}, 0xc?, {0x0?, 0x104aee294?, 0x1400030bd88?})
	/Users/johnathan/go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/sso@v1.9.0/api_op_ListAccountRoles.go:20 +0xc0
github.com/synfinatic/aws-sso-cli/sso.(*AWSSSO).GetRoles(0x14000430000, {0x126, {0x140000b6560, 0xc}, {0x140000b65b0, 0xf}, {0x1400046ade0, 0x24}})
	/Users/johnathan/Code/work/aws-sso-cli/sso/awssso.go:149 +0x254
github.com/synfinatic/aws-sso-cli/sso.fetchSSORole(0x222029373d6e656c?, 0x22656c6666756873?, 0x28636e756628203a?, 0x2029676e69727473?)
	/Users/johnathan/Code/work/aws-sso-cli/sso/cache.go:432 +0x130
created by github.com/synfinatic/aws-sso-cli/sso.(*Cache).addSSORoles
	/Users/johnathan/Code/work/aws-sso-cli/sso/cache.go:516 +0x3fc
```

On the second attempt, I ended up with half a dozen AWS SSO approval windows popping up, once I approved all of them, the cache updated with no errors. 

I did not receive the 2 second notification as far as I can tell. 

I'm in UK timezone, happy to do a screen share if it helps.

**Comment by colatricks** [comment]
Side note, `./aws-sso cache` seems to result in the above behaviour, sporadically. Sometimes it launches one AWS-SSO window then fails out, other times it's two/three.

**Comment by colatricks** [comment]
No joy - https://gist.github.com/colatricks/268bc0e6cb6829f609112019b61abf60 

I've uncommented the two lines in sso/awssso.go.

**Comment by synfinatic** [comment]
Another change.  

Also, please build your binary with race-detection which should provide more details on what's going on: `make build-race`

**Comment by synfinatic** [comment]
Those logs were very useful.  Thanks.

One thing that seems to be happening is that your AccessToken is showing up as Invalid.... which in theory shouldn't be happening, but is a random issue I've seen in the past with the AWS API.  Not sure if the extra threads are causing it to happen more often?

Anyways, hopefully the above change improves things.  Either way, I'd appreciate it if you ran with the `--level debug` flag and look  for messages like: `Unexpected AccessToken failure; refreshing: XXXXX`.   The included error message and how many times it is happening would be interesting to me as I'll probably want to talk to AWS about tit.  

Debug output does print out the AccountID's... which I know a lot of people consider sensitive... feel free to filter them out via  piping to `grep -v 'processing AccountId'` if you'd like.

**Comment by colatricks** [comment]
I think those latest changes have made it much more reliable - I'm not seeing any of the errors I was hitting previously. `--level debug` has shed some more light which might be useful: 

```
DEBUG   proccessed 360 results                       
DEBUG   Worker 5 processing AccountId: <redacted>  
DEBUG   proccessed 361 results                       
DEBUG   Unexpected AccessToken failure; refreshing: operation error SSO: ListAccountRoles, exceeded maximum number of attempts, 3, https response error StatusCode: 429, RequestID: 8475d47c-<redacted>-fb9f1d52cb8e, TooManyRequestsException: HTTP 429 Unknown Code 
DEBUG   Using RegisterClient cache for <redacted>     
DEBUG   Worker 2 processing AccountId: <redacted>  
DEBUG   proccessed 362 results                       
DEBUG   Created OIDC device code for <redacted> (expires in: 600s) 
DEBUG   exec command as array: /Applications/Firefox.app/Contents/MacOS/firefox ext+container:name=<redacted>&url=https%3A%2F%2Fdevice.sso.ap-southeast-2.amazonaws.com%2F%3Fuser_code%3DHDMM-SXQB&color=blue&icon=fingerprint 
DEBUG   Opened our URL with /Applications/Firefox.app/Contents/MacOS/firefox 
INFO    Waiting for SSO authentication...            
DEBUG   Worker 6 processing AccountId: <redacted>  
DEBUG   proccessed 363 results       
```
The above pops as you can see after almost several hundred results - rate limiting? 

Additionally even though it's popping a window for me to approve the SSO connection a few times in the process, this isn't actually stopping the processing of account ID's.

Also interestingly this appears after it's processed 25 results: 

`WARNING Fetching roles for 783 accounts, this might take a while... `

Not sure if the intention was for it to be hidden behind a WARNING label, but I don't see that detail in normal utilisation without the `debug` flag.

**Comment by synfinatic** [comment]
Yes, the default log level is `warn`.  Did you change the default log level to `error`?  

But yes, the error does sound like a rate limiting issue.  You can change the number of threads by editing the `~/.aws-sso/config.yaml` and adding a line like `Threads: 5`.
