### ISSUE TITLE
Sort list output by account alias

### ISSUE THREAD

**Issue by braun1928** [synfinatic/aws-sso-cli#466]
**Is your feature request related to a problem? Please describe.**
The browser shows the accounts sorted by `AccountName`, which is useful when we have `<team/app account>-<environment>` pattern. Unfortunately the `aws-sso-cli` sorts by `AccountNumber`, making accounts separate from each other when listing, making a bit difficult to find.

**Describe the solution you'd like**
An option to sort the list output by other values, like `AccountAlias`, which can be also defined as default in the configuration file.

**Describe alternatives you've considered**
I know I can use `grep` or Command + F, or change the output fields and `| sort`, but it would be nice not using it, and most likely, faster.

**Comment by synfinatic** [comment]
Are you okay with sorting by the first column?  You can always override/select the fields and their order on the CLI or via [the config file](https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md#ListFields)

**Comment by synfinatic** [comment]
Also, thoughts on how to sort when dealing with different cases?   Basically is `a` equivalent to `A` or does it come after `Z`?

**Comment by braun1928** [comment]
> Are you okay with sorting by the first column? You can always override/select the fields and their order on the CLI or via [the config file](https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md#ListFields)

Yeah, that's what I was started doing -- still need to remember to `| sort` the output, and ignore the header line that stays in the middle of the output.

> Also, thoughts on how to sort when dealing with different cases? Basically is `a` equivalent to `A` or does it come after `Z`?

I'm fine with either -- `sort.Strings()` differentiates the case, AWS SSO main page ignores case. In my case, majority of the accounts are all lower case, so doesn't matter _that_ much.

---
I saw a minor thing: the account number is parsing to a number, so drops the leading 0. Not a huge deal, but caught my eye.
