### ISSUE TITLE
exec by alias

### ISSUE THREAD

**Issue by mrsufgi** [synfinatic/aws-sso-cli#468]
**Is your feature request related to a problem? Please describe.**
I swap profiles fast and want to avoid going through the prompt whenever I want to assume a new role. Currently I'm doing it via the -p argument, but it would have been helpful if exec by alias was also possible.

Also, I use `direnv` to parse folder names and assume roles based on folders, quite nifty :) so if my account alias is "mrsufgi-prod" and my folder is "mrsufgi-prod" it triggers aws-sso exec with --alias `$(basename $(expand_path .))` 

**Describe the solution you'd like**
Adding a new flag for `--alias` in the `exec` command

**Describe alternatives you've considered**
Predefine env variables for profiles

**Comment by synfinatic** [comment]
Can you not use the `eval` command?

ie, place the following in your `.envrc`:  `eval $(aws-sso eval -p <profile>)`

that would set the appropriate `$AWS_XXXX` variables for you?
