### ISSUE TITLE
Long waiting for passphrase and url not opened correctly

### ISSUE THREAD

**Issue by tmpm697** [synfinatic/aws-sso-cli#478]
**Output of `aws-sso version`:**
```
INFO[0000] open /home/user/.aws-sso/cache.json: no such file or directory
AWS SSO CLI Version 1.9.10 -- Copyright 2021-2022 Aaron Turner
11ec65288f78702a5e80078c04e0ef8b4ac7cb67 (v1.9.10) built at 2023-03-03T22:12:06+0000
```

**Describe the bug:**
1. run `aws-sso` you have to wait for `minutes` for it to prompt passphrase.
2. `aws-sso` opening url works by just pasting `ext+container <...>` to google

**To Reproduce:**
 1. aws-sso
 2. enter info to above command
 3. aws-sso #re-run again

**Expected behavior:**
1. fast passphrase prompt
4. open url in container correctly

**Screenshots:**

**Desktop (please complete the following information):**
 - OS: archlinux
 - Version: latest

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
│ ABCDEF:
│ │ SSORegion: us-east-2
│ │ StartUrl: https://d-my-sso-xxxx.awsapps.com/start
│ │ DefaultRegion: us-east-2
DefaultRegion: us-east-2
ConsoleDuration: 60
CacheRefresh: 168
AutoConfigCheck: true
UrlAction: open-url-in-container
ConfigProfilesUrlAction: open-url-in-container
UrlExecCommand:
│ - /usr/bin/firefox-beta
│ - "%s"
LogLevel: trace
HistoryLimit: 20
HistoryMinutes: 1440
```

I also have a container named `ABCDEF`

**Comment by tmpm697** [comment]
i thought it will open use native firefox multi container plugin, it's not. should clearly this with a link in readme.

**Comment by tmpm697** [comment]
`open-url-in-container` and `granted-containers` words actually refer to plugins that need to be installed.

firefox comes with its container support from mozilla named `multi-account-containers` but still can't open a container with a link from cli, check: https://github.com/mozilla/multi-account-containers/issues/365

Ah just re-check, you gave the links in docs :)

**Comment by synfinatic** [comment]
oh, you're talking about yet another container plugin... it's not actually shipped with Firefox by default and needs to be installed: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
