### ISSUE TITLE
AccountName and AccountAlias seem to be confused

### ISSUE THREAD

**Issue by iainelder** [synfinatic/aws-sso-cli#483]
**Output of `aws-sso version`:**

```console
$ aws-sso-cli version
AWS SSO CLI Version 1.9.10 -- Copyright 2021-2022 Aaron Turner
11ec65288f78702a5e80078c04e0ef8b4ac7cb67 (v1.9.10) built at 2023-03-03T22:12:06+0000
```

**Describe the bug:**

Set `AWS_SSO_CONFIG` to point to the config file. See below for the base configuration. The `ProfileFormat` part varies.

Set `AWS_CONFIG_FILE` to point to a temporary location for the AWS CLI profiles config.

Use this command to generate the profiles:

```bash
rm $AWS_CONFIG_FILE && \
rm ~/.aws-sso/cache.json && \
aws-sso-cli config-profiles --level=debug --force && \
aws configure list-profiles
```

Add this to the base config:

```yaml
ProfileFormat: "{{.SSO}}:{{.AccountId}}:{{.RoleName}}"
```

The final output is correct. There are 5 profiles and the name shows all the field values (Even though the debug output only shows 4 accounts.)

```text
INFO    open /home/isme/.aws-sso/cache.json: no such file or directory 
INFO    Refreshing AWS SSO role cache for sandbox, please wait... 
DEBUG   Worker 4 processing AccountId: 111111111111  
DEBUG   Worker 3 processing AccountId: 222222222222  
DEBUG   Worker 2 processing AccountId: 333333333333  
DEBUG   Worker 1 processing AccountId: 444444444444  
DEBUG   proccessed 1 results                         
DEBUG   proccessed 2 results                         
DEBUG   proccessed 3 results                         
DEBUG   proccessed 4 results                         
DEBUG   path = /home/isme/Repos/Personal/github/aws-config/.aws/config 
sandbox:222222222222:AdministratorAccess
sandbox:555555555555:AdministratorAccess
sandbox:333333333333:AdministratorAccess
sandbox:444444444444:AdministratorAccess
sandbox:111111111111:AdministratorAccess
```

Add this to the base config:

```yaml
ProfileFormat: "{{.SSO}}:{{.AccountId}}:{{.RoleName}}:{{.AccountName}}"
```

The final output is wrong because the account name is blank.

```text
INFO    open /home/isme/.aws-sso/cache.json: no such file or directory 
INFO    Refreshing AWS SSO role cache for sandbox, please wait... 
DEBUG   Worker 4 processing AccountId: 111111111111  
DEBUG   Worker 1 processing AccountId: 222222222222  
DEBUG   Worker 2 processing AccountId: 333333333333  
DEBUG   Worker 3 processing AccountId: 444444444444  
DEBUG   proccessed 1 results                         
DEBUG   proccessed 2 results                         
DEBUG   proccessed 3 results                         
DEBUG   proccessed 4 results                         
DEBUG   path = /home/isme/Repos/Personal/github/aws-config/.aws/config 
sandbox:111111111111:AdministratorAccess:
sandbox:555555555555:AdministratorAccess:
sandbox:333333333333:AdministratorAccess:
sandbox:444444444444:AdministratorAccess:
sandbox:222222222222:AdministratorAccess:
```

Add this to the base config:

```yaml
ProfileFormat: "{{.SSO}}:{{.AccountId}}:{{.RoleName}}:{{.AccountAlias}}"
```

The final output is wrong because it gives the account name instead of the alias. And instead of 5 profiles there are only 2.

```text
INFO    open /home/isme/.aws-sso/cache.json: no such file or directory 
INFO    Refreshing AWS SSO role cache for sandbox, please wait... 
DEBUG   Worker 3 processing AccountId: 111111111111  
DEBUG   Worker 1 processing AccountId: 222222222222  
DEBUG   Worker 2 processing AccountId: 333333333333  
DEBUG   Worker 4 processing AccountId: 444444444444  
DEBUG   proccessed 1 results                         
DEBUG   proccessed 2 results                         
DEBUG   proccessed 3 results                         
DEBUG   proccessed 4 results                         
DEBUG   path = /home/isme/Repos/Personal/github/aws-config/.aws/config 
sandbox:333333333333:AdministratorAccess:Desktop
sandbox:444444444444:AdministratorAccess:CodeArtifact
```

None of the account in my test organization have an alias as given by IAM GetAccountAliases.

The account names in my test setup are:

* 111111111111: Test API
* 222222222222: AWS IQ
* 333333333333: Desktop
* 444444444444: CodeArtifact
* 555555555555: Organization Management Account

It looks like account names with spaces cause the AccountAlias field to silently fail.

**Expected behavior:**

I would expect the `AccountName` field to output the account names as above.

I would expect the `AccountAlias` field to output nothing.

**Additional context**:

This could be a regression of #201 .

**Contents of `~/.aws-sso/config.yaml`:**

Base configuration is:

```yaml
SSOConfig:

    sandbox:
        SSORegion: eu-west-1
        StartUrl: https://d-aaaaaaaaaa.awsapps.com/start/
        DefaultRegion: eu-west-1


ConsoleDuration: 720
UrlAction: "granted-containers"
ConfigProfilesUrlAction: "granted-containers"
UrlExecCommand:
    - "/usr/bin/firefox"
    - "%s"
LogLevel: "info"
```

**Comment by iainelder** [comment]
I can work around the problem with the spaces by using this sprig expression to replace the spaces with dashes: `{{.AccountAlias | replace " " "-"}}`.

**Comment by synfinatic** [comment]
Not sure, but I think you have `AccountName` and `AccountAlias` backwards??

 * AccountName is defined by you in the `~/.aws-sso/config.yaml` file.
 * AccountAlias is defined by your AWS Account owner in AWS.

https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md#name

That said, I the [docs for `AccountName` here](https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md#name) are incorrect... it will not fail back to AccountAlias as of #201 

If you want that behavior, use:  `ProfileFormat: "{{.SSO}}:{{.AccountId}}:{{.RoleName}}:{{FirstItem .AccountName .AccountAlias}}"`

As for the missing SSO tag... are you saying doing `{{ .AccountAlias | replace " " "-" }}` fixed that???

**Comment by iainelder** [comment]
Hi, thanks for the response.

I'm not able to try the suggestion any more because I switched to using another tool for my CLI profiles.

I'll close this now because I don't need help any more.
