### ISSUE TITLE
Profile aliases

### ISSUE THREAD

**Issue by viraptor** [synfinatic/aws-sso-cli#484]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to have two entries generated for each profile - the autogenerated one and a custom one.

**Describe the solution you'd like**

I'd like to see a config like:
```
                Roles:
                    <Role Name>:
                        Profile: <ProfileName>
        -->             AltProfile: <ProfileName> 
                        DefaultRegion: <AWS_DEFAULT_REGION>
                        Tags:  # tags specific for this role (will override account level tags)
                            <Key1>: <Value1>
                            <Key2>: <Value2>
                        Via: <Previous Role>  # optional, for role chaining
                        SourceIdentity: <Source Identity>
```
Which both uses the default template and adds the `AltProfile` as a profile with exactly the same config.

**Describe alternatives you've considered**

I know I can already set Accounts -> ...  -> Roles -> ... -> Profile name, but that overrides the default. I'd like to be able to use both a fully descriptive names in docs (department-project-environment-access style template) and a short name for things I work on all the time so it's just `pmd` or whatever makes sense there.

**Comment by synfinatic** [comment]
Can you explain more about when/how this alternate / long form profile name will be used?  Having two names for the same role creates a number of issues and honestly isn't going to happen.  But if you're just looking for a "comment" then that's very different.

**Comment by viraptor** [comment]
My usage for this is as mentioned in the issue - specifically, we've got many profiles in the company and teams may have different preferences and ways of documenting them. Mostly this is covered by the naming pattern already and is good to keep in common / in the docs.

So usage 1 (full names) is for great for documentation/runbooks ("To frobnicate the teleporter run `aws-sso exec -p the-long-descriptive-role -- some command`"). Either you're using the default pattern, or from the name you know exactly what was intended there. This also helps with scripts that everyone can use because the role naming is consistent.

But writing that each time in practice is not great - it's a lot of spam in the history file, it overflows on smaller terminals and effectively in a day-to-day work I don't care about the company-wide or team-wide standard configuration. Instead I want to achieve quick commands.

So usage 2 (short names) is for the terminal - I want to be able to run `ase ppd foo` instead of `aws-sso exec -p project-production-developer -- whatever foo alias expands to`.

Ideally I want to have both naming conventions available at the same time since sometimes I work on my usual part of the project that I have aliases / custom scripts for, and sometimes I work on something else and rely on the docs / runbooks.

Of course you can also tell me that's out of scope and to just alias `ase-ppd` instead :)

**Comment by synfinatic** [comment]
For docs/runbooks why not use the `--account` and `--role` flags instead of an arbitrary profile name?   That would be always explicit, portable and clear.  It also wouldn't depend on everyone having the same `~/.aws-sso/config.yaml` file to share these aliases.

I'll be honest, this seems very corner case use case and I'm not even sure I'd accept a pull request that adds it... really would depend on how much work it would be to maintain the code and would require a lot of unit tests.  If that's something you're interested in doing let me know and we can talk further.  Otherwise, I'll close this as won't fix.

**Comment by viraptor** [comment]
> For docs/runbooks why not use the --account and --role flags instead of an arbitrary profile name?

Smart!
