### ISSUE TITLE
IDE integration

### ISSUE THREAD

**Issue by wparad** [synfinatic/aws-sso-cli#487]
### The short version:
What should my VS Code launch.json contain to execute aws-sso and inject the credentials into the debug process?

### Longer version:
It isn't clear to me how to use this library when running a debugging process through an IDE. Often you don't fully control the process initiation flow, which usually means there is no good way to run the debugging process  as part of `aws-sso exec`.

The way this is done with other AWS SSO providers is via the ECS metadata service, but the `aws-sso` cli doesn't support the ECS metadata.

---
At the very least an example of vs code would be nice to be able to understand what needs to be done to get this working. Because as it is without the metadata service, it isn't clear how to use this library for 99% of our use cases.

**Comment by synfinatic** [comment]
I don't know or use VS Code.  I use vim :)   

But if you want to inject variables, you want `aws-sso eval`.  That plus the necessary arguments will generate your ENV vars.

Does that help?

**Comment by wparad** [comment]
How do you debug code without an IDE?

**Comment by synfinatic** [comment]
![magic](https://media.tenor.com/DNCBqbguizsAAAAd/magic.gif)

**Comment by wparad** [comment]
Okay so this works I think partially for vscode:
```json
{
      "type": "node-terminal",
      "request": "launch",
      "name": "Debug with AWS Credentials",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "command": "eval $(aws-sso eval  --account AWS_ACCOUNT_ID --role ROLE_NAME) && npm run COMMAND"
    },
    ```

Or `npx nodemon run.js` I have no idea what happens when the credentials expire, but I guess we'll find out.

**Comment by wparad** [comment]
I'm going to close this issue with the expectation that this works for now, I'm going to see if we run into any problems like this. Thank you.
