### ISSUE TITLE
Credential Management Flow

### ISSUE THREAD

**Issue by wparad** [synfinatic/aws-sso-cli#488]
It would be nice to see a flow diagram of the whole process including what happens, where the credentials are saved, how they are encrypted, when the credentials are expired.

**Comment by synfinatic** [comment]
Not really sure what value a diagram would provide?  Specifically, the whole storage & encryption part is based on the [SecureStore](https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md#securestore--jsonstore) that you choose and is not specific to `aws-sso`.

As for "when the credentials are expired" `aws-sso list` will answer that.

**Comment by wparad** [comment]
I don't want to know "when the credentials will expire", I was looking to know what the tool does when it encountered expired credentials. But I think the answer is nothing.

Which brings up the question how do I "sign out" and terminate all credentials currently saved?

**Comment by synfinatic** [comment]
Oh.  If you try to use expired credentials then it will automatically refresh them when you try to use the expired credentials.  Just like if the credentials weren't cached in the first place.

https://github.com/synfinatic/aws-sso-cli/blob/main/docs/commands.md#flush
