### ISSUE TITLE
Regex AccountAlias

### ISSUE THREAD

**Issue by Gavin89** [synfinatic/aws-sso-cli#504]
**Is your feature request related to a problem? Please describe.**
We have many aws accounts that all start with the same name format <company>-<env>-<5 random num> and it would be good to search a specific string in the account name instead of typing the full one

**Comment by synfinatic** [comment]
when are you trying to search???  Have you looked at `aws-sso list --prefix` and enabled shell auto-complete support via `aws-sso completions`.

**Comment by synfinatic** [comment]
You could also use `regexReplaceAll` from [sprig](http://masterminds.github.io/sprig/strings.html) in conjunction with [ProfileFormat](https://github.com/synfinatic/aws-sso-cli/docs/config.md#ProfileFormat) to generate more friendly names.  Something like:

`ProfileFormat: {{ regexReplaceAll "^[0-9]{5}(.*)" .AccountAlias "${1}" }}:{{ .RoleName }}"`

Would strip the leading random 5 digit numbers from the account alias.  Of course if you have some accounts without the random 5 digits then things get more complicated.

Or you can manually set a friendly name via [Name](https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md#name) in the config file for each account.

**Comment by Gavin89** [comment]
If I wanted to exec into a specific AccountAlias via cli, is this possible? `aws-sso exec --account-alias=company-tmp-stg01`

**Comment by synfinatic** [comment]
@Gavin89  FYI, if you want to build from source you should be able to test it now.

**Comment by Gavin89** [comment]
Thank you!

**Comment by Gavin89** [comment]
Works great! exactly what I wanted, thank you.
