### ISSUE TITLE
Set AWS_PROFILE when running aws-sso

### ISSUE THREAD

**Issue by Moulick** [synfinatic/aws-sso-cli#535]
**Is your feature request related to a problem? Please describe.**
There are some script/tools that utilize specifically the `AWS_PROFILE` env var to do stuff. The main one that comes to mind is https://github.com/romkatv/powerlevel10k. This uses the `AWS_PROFILE` for configuring the PS1

**Describe the solution you'd like**
export `AWS_PROFILE` same as `AWS_SSO_PROFILE`

**Additional context**
Consideration is the behaviour of aws-sso-profile wrapper that does not work when `AWS_PFOFILE` is set

**Comment by synfinatic** [comment]
No, this is not possible.  `$AWS_PROFILE` is owned by the AWS SDK.  Settings this value along with the other variables can cause problems.

If you wish to use this integration you will either need to add support for `$AWS_SSO_PROFILE` to powerlevel10k or utilize aws-sso through the `$AWS_PROFILE` environment variable and then use aws-sso by setting your `$AWS_PROFILE` variable manually.  See the [config-profiles](https://github.com/synfinatic/aws-sso-cli/blob/main/docs/commands.md#config-profiles) command for more info.
