### ISSUE TITLE
Honor `$AWS_CONFIG_FILE` env variable

### ISSUE THREAD

**Issue by argoyle** [synfinatic/aws-sso-cli#540]
**Is your feature request related to a problem? Please describe.**
I'm working for multiple clients and have split my AWS configuration in different directories by help of direnv and setting the env-vars AWS_CONFIG_FILE/AWS_SHARED_CREDENTIALS_FILE to point at a directory specific for each client. aws-sso seems to ignore those and always updates ~/.aws/config.

**Describe the solution you'd like**
A possibility to handle config per client somehow

**Comment by synfinatic** [comment]
This sounds like a good idea!  `AWS_CONFIG_FILE` makes a lot of sense, but I'm not really sure what aws-sso should do with `AWS_SHARED_CREDENTIALS_FILE`?

**Comment by synfinatic** [comment]
Another question: is this mapping of roles to config files static or dynamic?  Ie: is this something you want to manage outside of aws-sso (managing this environment variable to change where the same roles get written to) or something you really want to set & forget (adding this to the aws-sso config file).

**Comment by argoyle** [comment]
You're probably correct regarding the credentials-file, I just mentioned it since I set that along with the config-var.

I handle this using direnv today so in each of my client-directories I have a .envrc-file which defines where the AWS-tooling should look for config and credentials. I actually already added the `AWS_SSO_CONFIG` to my files in the hope that the rest should "just work ™️" 😊

**Comment by synfinatic** [comment]
So looking at the code... it should work today?

I just tested with `AWS_CONFIG_FILE=~/config aws-sso config-profiles` and wrote out everything to the specified alternate file instead of `~/.aws/config`

**Comment by argoyle** [comment]
Hmmm, config-profiles seems to do the correct thing. When I just ran aws-sso config it asked if it should update ~/.aws/config though.

**Comment by argoyle** [comment]
Even more strange. In one of my client directories config-profiles did this:
```
The following changes are proposed to /Users/argoyle/.aws/config:
--- /Users/argoyle/.aws/config
+++ /Users/argoyle/.aws/config.new
@@ -1 +1,23 @@
+# BEGIN_AWS_SSO_CLI
+
...profiles
+
+# END_AWS_SSO_CLI


Modify /Users/argoyle/.aws/config with proposed changes?: No
The following changes are proposed to /Users/argoyle/Source/CustomerProjects/<client>/.aws/config:
--- /Users/argoyle/Source/CustomerProjects/<client>/.aws/config
+++ /Users/argoyle/Source/CustomerProjects/<client>/.aws/config.new
@@ -13,3 +13,22 @@
 output = json
+# BEGIN_AWS_SSO_CLI
+
...profiles
+
+# END_AWS_SSO_CLI


Modify /Users/argoyle/Source/CustomerProjects/<client>/.aws/config with proposed changes?: Yes
```

Maybe my aws-sso config was strange there. I think I've already set that up earlier. Will try in another directory.

**Comment by argoyle** [comment]
Another client was fine so probably something strange in my config

**Comment by argoyle** [comment]
Aaah, I had enabled AutoConfigCheck in that config. That seems to want to update the default path always.

**Comment by synfinatic** [comment]
Awesome.  that helps a lot.
