### ISSUE TITLE
Consider switching to toml?

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/aws-sso-cli#549]
the yaml config is getting really big and has many levels.  Does switching to TOML make sense?  Not sure if the dot notation is better/worse?  Would need to come up with a template and decide.

Or is this whole config file bad and what we need is a DB with UI on top?  ie: #351

**Comment by Moulick** [comment]
I would definitely prefer YAML over TOML. Yam is much more easier to read/format compared to toml

**Comment by synfinatic** [comment]
Thanks for the feedback @Moulick
