### ISSUE TITLE
Guided setup using aws-sso config --advanced does not work as expected 

### ISSUE THREAD

**Issue by skrings** [synfinatic/aws-sso-cli#563]
**Output of `aws-sso version`:**
```
Example output:
AWS SSO CLI Version 1.13.0 -- Copyright 2021-2023 Aaron Turner
3e719f3572a8ad4a7455e328d39ee704d9bfcc06 (v1.13.0) built at 2023-08-21T19:11:01+0000
```

**Describe the bug:**
The path to the browser to use is optional. When using the guided setup, it is not possible to leave the browser path empty to use the system default.

> Specify path to browser to use. Leave empty to use system default (Browser)

**To Reproduce:**
 1. Run `aws-sso config --advanced`
 2. Continue until step to optional specify the path to browser to use
 4. Leave blank, hit \<enter\>
 5. 🤷‍♂️ 

**Expected behavior:**
The step to configure the path to the browser should accept empty input and fall back to system default.

**Screenshots:**
<img width="1176" alt="aws_sso_config" src="https://github.com/synfinatic/aws-sso-cli/assets/204874/81c6e8b8-18df-412e-be1a-354f4b5832df">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13.5.1 (22G90)

**Additional context:**
The `--advanced` flag was introduced with release 1.13.0. https://github.com/synfinatic/aws-sso-cli/releases/tag/v1.13.0

**Contents of `~/.aws-sso/config.yaml`:**

Not applicable as I am in the process to generate a `config.yaml`.

**Comment by synfinatic** [comment]
thanks for the report!
