### ISSUE TITLE
define a default Role in the config

### ISSUE THREAD

**Issue by TheRojam** [synfinatic/aws-sso-cli#566]
**Is your feature request related to a problem? Please describe.**

I am using aws-sso-cli due to the fact, that i have multiple aws accounts, where i manage multiple aws services.
With the time, it got very inconvenient to use always the sso website to get the credentials.
One the onside i use multiple accounts, on the other they've got different roles, but depending on the system i always use the same role.

**Describe the solution you'd like**
define a default role which is to use for every account, in the config.

**Describe alternatives you've considered**
Always manually choose the same role.

**Comment by synfinatic** [comment]
I don't see a need for this since you can create a simple [shell alias](https://tldp.org/LDP/abs/html/aliases.html) to do this for you?
