### ISSUE TITLE
ability to set prompt when using `exec`

### ISSUE THREAD

**Issue by sstrong99** [synfinatic/aws-sso-cli#577]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set the command prompt when running `aws-sso exec`. For example i'd like to do something like this
```
aws-sso exec ... '/bin/bash --rcfile <(cat ~/.bashrc; echo "export PS1=\"aws $ \"")'
```
Currently, when I run that command i get the error
```
FATAL   Error running command: fork/exec /bin/bash --rcfile <(cat ~/.bashrc; echo "export PS1=\"aws $ \""): no such file or directory
```

**Describe the solution you'd like**
either a fix that allows the above example to work, or an argument like `--prompt` that can be passed to `aws-sso` to set the command prompt inside the shell. (or some help to figure out how to get the above command to work)

**Describe alternatives you've considered**
N/A

**Additional context**
I have run in to this problem on mac. haven't experimented with it on linux

**Comment by synfinatic** [comment]
why not just use an if/then/else block in your ~/.bashrc to set the prompt and skip that mess?   Any of the managed variables should do: https://github.com/synfinatic/aws-sso-cli/blob/main/docs/commands.md#managed-variables

**Comment by sstrong99** [comment]
thanks, that's a good idea! The one downside is that it doesn't give control over the prompt to the caller of `aws-sso`. that's a minor thing though

**Comment by synfinatic** [comment]
You also have access to https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md#envvartags so I really have a hard time imaging something reasonable that can't be done this way.    Of course my definition of "reasonable" might differ from yours, but this feature request seems like an ugly hack honestly.
