### ISSUE TITLE
Use desktop notifications for login user code

### ISSUE THREAD

**Issue by dbalan** [synfinatic/aws-sso-cli#650]
**Is your feature request related to a problem? Please describe.**
This is related on #572; This workflow breaks when the sessions is authenticated using `credential_process` with aws-cli. AWS cli silently calls `aws-sso-cli` and the console has no access to any outputs.

**Describe the solution you'd like**
Would you consider sending out a desktop notifications (if the platform allows it and `dbus` gods works) with something like https://github.com/gen2brain/beeep

**Describe alternatives you've considered**
None

**Additional context**
Would be happy to work on it.

**Comment by synfinatic** [comment]
Not worth doing/relevant as the direction of aws-sso is to move towards a dedicated login command/workflow.  Hence, no need for this IMHO.   See #291

**Comment by dbalan** [comment]
Sounds good! Waiting for the release :)
