### ISSUE TITLE
command argument of aws-sso exec is not parsed as expected

### ISSUE THREAD

**Issue by lovelykd** [synfinatic/aws-sso-cli#722]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.14.2 -- Copyright 2021-2023 Aaron Turner
792f11ec86a5ce6683ba2df7cb544e4f76f2431b (v1.14.2) built at 2023-10-20T03:36:46+0000
```

**Describe the bug:**
aws-sso attempts to parse the --version as a flag of exec rather than an argument of the command to be executed

**To Reproduce:**
```
aws-sso exec --arn=arn:aws:iam::****:role/**** aws --version
aws-sso: error: unknown flag --version
```

**Expected behavior:**
aws version be printed

**Screenshots:**
Not needed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2

**Additional context:**

It can be bypassed by adding a double dash, but it's not ideal
```
aws-sso exec --arn=arn:aws:iam::****:role/**** -- aws --version
```
the following will also work (bear with me, that is an bad example) probably because of the pr for https://github.com/synfinatic/aws-sso-cli/issues/93
```
aws-sso exec --arn=arn:aws:iam::****:role/**** aws s3 --version 
```

**Contents of `~/.aws-sso/config.yaml`:**
Not needed

**Comment by synfinatic** [comment]
I'll be honest, this is pretty standard for how shell arg processing works.  issue is really in the kong library: https://github.com/alecthomas/kong.  I'll keep an eye out for a fix, but if you know anyone interested in contributing a fix I suspect that would help greatly.
