### ISSUE TITLE
Support exec / eval for non-sso profiles

### ISSUE THREAD

**Issue by latacora-paul** [synfinatic/aws-sso-cli#743]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to use other types of profiles (like source_profile & role_arn assumptions) but would still like to use aws-sso to populate env vars for a child process. Today I can't do this because aws-sso seems to only supports those operations using the SSO profiles that it generates/maintains.

**Describe the solution you'd like**
It shouldn't matter where my profile came from or how it is defined, if it's valid according to the AWS SDK I should be able to use it with `aws-sso exec` and `aws-sso eval`.

**Describe alternatives you've considered**
I can write my own script to bypass aws-sso and do the role assumption and populate the env vars before launching a child process. For child processes that support all the profile types I can simply set AWS_PROFILE and let the child process do the role assumption instead.

**Comment by synfinatic** [comment]
Hi @latacora-paul,

So depending on your use case this is either supported today or realistically never going to happen as being out of scope.  

Specifically, aws-sso does support [role chaining](https://synfinatic.github.io/aws-sso-cli/config/#via).  Note, I don't claim to support every use case with this as that is not the intent.

For what is deemed out of scope, basically anything that wouldn't use directly or indirectly an IAM Role managed by [AWS IAM Identity Center](https://aws.amazon.com/iam/identity-center/).   That would include IAM Users, IAM Roles integrated with SAML auth or other IAM Roles outside of Identity Center that don't require role chaining.

LMK if you have any questions.
