### ISSUE TITLE
Use official Mozilla FireFox container tabs?

### ISSUE THREAD

**Issue by jabberwock** [synfinatic/aws-sso-cli#760]
**Is your feature request related to a problem? Please describe.**
I'd like to use my official Mozilla Firefox container tabs with this. It does appear that the proper command format is here:

https://github.com/synfinatic/aws-sso-cli/blob/60cc678d3c7e85fd2ec9f7de22208c2f629ab732/internal/url/url.go#L64

But I am not sure how to set up my config so that it uses the official plugin rather than the off-brand plugin. 

Here is the official documentation:
https://support.mozilla.org/en-US/kb/how-use-firefox-containers

This feature relies on the official extension:
https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

I appreciate any support you may offer.

**Comment by synfinatic** [comment]
should be able to follow: https://synfinatic.github.io/aws-sso-cli/config/#open-url-in-firefox-container

**Comment by synfinatic** [comment]
@jabberwock  did that work?

**Comment by jabberwock** [comment]
Yes. Thank you!

**Comment by aesanch2** [comment]
@synfinatic is this still supported in the latest version? It doesn't look like there's an option for `open-url-in-firefox-container` and the documented option opens a new tab with the the `ext-container` command as a search bar query.

<img width="655" alt="image" src="https://github.com/user-attachments/assets/bbc6ea23-d780-42b7-b5df-4e56792d6fff">

**Comment by synfinatic** [comment]
@aesanch2 please open a new ticket and fill out the form.  Thanks.
