### ISSUE TITLE
AWS_SSO_SESSION_DURATION should use RFC3339 format

### ISSUE THREAD

**Issue by arkanes** [synfinatic/aws-sso-cli#837]
**Is your feature request related to a problem? Please describe.**
AWS_SSO_SESSION_EXPIRATION just uses [Time.String](https://pkg.go.dev/time#Time.String) to format the timestamp. This is not in a standardized format, and per the documentation for Time.String, should only be used for debugging.

Awsume and aws-vault use [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339) formatted strings for their equivalent environment variables, e.g. `2024-04-19T12:43:38-07:00`

**Describe the solution you'd like**
Setting the value of AWS_SSO_SESSION_EXPIRATION to be formatted using RFC3339

**Describe alternatives you've considered**
if there are backwards compatibility concerns, a flag to opt into this behavior, and/or setting an additional environment variable in this format should address them

**Additional context**

**Comment by synfinatic** [comment]
Are you trying to parse the timestamp in code or is this in your opinion a question of human readability?  Or is it just you like RFC's? :D

**Comment by synfinatic** [comment]
Is epoch seconds viable?  I ask, because parsing epoch seconds tends to be the lowest common denominator for the `date` command and every language under the sun.  Originally, I almost used that, but it tends to be painful for humans.
