### ISSUE TITLE
fix brew build 

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/aws-sso-cli#899]
Fix build for homebrew: https://github.com/Homebrew/homebrew-core/pull/174439

**Comment by chenrui333** [comment]
@synfinatic not sure if I am doing correctly, but I am seeing this

```
$ aws-sso completions --no-config-check
WARNING No config file found!  Will now prompt you for a basic config...

**********************************************************************
* Do you have questions?  Do you like reading docs?  We've got docs! *
* https://github.com/synfinatic/aws-sso-cli/blob/main/docs/config.md *
**********************************************************************


✗ SSO Start URL Hostname (XXXXXXX.awsapps.com): |
```

**Comment by synfinatic** [comment]
Hi @chenrui333,

I'm not sure what you're trying to do?  The brewfile doesn't try running the `completions` command: https://github.com/Homebrew/homebrew-core/blob/master/Formula/a/aws-sso-cli.rb#L28

But basically, you don't have a valid `~/.aws-sso/config.yaml` so you're going to get the configuration wizard, even with `--no-config-check`.  This is expected.  

Without a valid config.yaml file, there really isn't much functionality possible.  And even with a "dummy" config file, all the functionality requires you to authenticate to your SSO provider via a javascript enabled web browser.

**Comment by chenrui333** [comment]
I am running after `brew install`, not running as part of `brew install`

**Comment by chenrui333** [comment]
also I am gonna rewrite the formula and not using `make install` (there is some ldflags I need to apply `-s -w` to strip debug info)

**Comment by synfinatic** [comment]
> I am running after `brew install`, not running as part of `brew install`

Sorry, I have no idea what you're trying to say.  Are you asking for general technical support or trying to resolve the issue that once existed, but no longer exists here: https://github.com/Homebrew/homebrew-core/pull/174439

**Comment by chenrui333** [comment]
that is fine. it is what it is.
