### ISSUE TITLE
config-profiles ignores url handler config and defaults to open

### ISSUE THREAD

**Issue by zonywhoop** [synfinatic/aws-sso-cli#945]
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.16.1 -- Copyright 2021-2023 Aaron Turner
Homebrew (1.16.1) built at 2024-06-13T22:59:35Z
```

**Describe the bug:**
Running `aws-sso config-profiles` ignores the configured `UrlAction` and instead uses `open` for all profiles.  This happens also if specifying `-u open-url-in-container` on the command line to config-profiles as well.

**To Reproduce:**
 1. Create a config with a set UrlAction other than `open`
 2. Run `aws-sso config-profiles` and see the produced output

**Expected behavior:**
The built profiles for `~/.aws/config` should either not specify `-u open` or the vale provided should be the value set in `UrlAction` in the config.yaml file.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.5

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
  Default:
    SSORegion: us-east-1
    StartUrl: https://d-xxxxxxxxxx.awsapps.com/start
    DefaultRegion: us-east-1
    Accounts:
      111111111111111:
        Name: work-primary
        Roles:
          AdministratorAccess:
            Profile: work-primary
      22222222222:
        Name: work-prod
        Roles:
          AdministratorAccess:
            Profile: work-prod
      33333333333:
        Name: work-staging
        Roles:
          AdministratorAccess:
            Profile: work-staging
      44444444444:
        Name: work-dev
        Roles:
          AdministratorAccess:
            Profile: work-dev
ConsoleDuration: 720
CacheRefresh: 168
UrlAction: open-url-in-container
UrlExecCommand:
  - /Applications/Firefox.app/Contents/MacOS/firefox
  - "%s"
LogLevel: error
DefaultSSO: Default
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ .SSO }}:{{ .AccountId }}:{{ .RoleName }}"
FullTextSearch: true

```

** Contents of `~/.aws/config`
```
# BEGIN_AWS_SSO_CLI_Default
[profile work-prod]
credential_process = /opt/homebrew/bin/aws-sso -u open -S "Default" process --arn arn:aws:iam::222222222222:role/AdministratorAccess
region = us-east-1

[profile work-primary]
credential_process = /opt/homebrew/bin/aws-sso -u open -S "Default" process --arn arn:aws:iam::111111111111:role/AdministratorAccess
region = us-east-1

[profile work-staging]
credential_process = /opt/homebrew/bin/aws-sso -u open -S "Default" process --arn arn:aws:iam::333333333333:role/AdministratorAccess
region = us-east-1


[profile work-dev]
credential_process = /opt/homebrew/bin/aws-sso -u open -S "Default" process --arn arn:aws:iam::444444444444:role/AdministratorAccess
region = us-east-1

# END_AWS_SSO_CLI_Default
```

**Comment by synfinatic** [comment]
Hi @zonywhoop, this is actually intended... things like `open-in-container` is really only relevant for the `console` command which opens the AWS Console in your browser.  `aws-sso` never does SSO authentication in a container, because that will force you to re-authenticate with your SSO provider for each role.

A complete list of valid open methods for `config-profiles` is documented here: https://synfinatic.github.io/aws-sso-cli/commands/#config-profiles

**Comment by zonywhoop** [comment]
Based on my use-case / experience that is not how it is operating.  

This is my use case: I'm a contractor working for many clients and each client has an SSO endpoint.  I have a matching firefox container for each of those so I can keep sessions clean between them. In my config I'm defining an SSO per client and then all of their accounts and the profiles we use in our IaC as manual overrides to account for this.

I've manually modified the `~/.aws/config` to remove `-u open` and using terraform / terragrunt / opentufo I'm able to successfully auth using the correct container in firefox on the first run and deploy resources across multiple accounts without any issues or re-auth's having to occur. So for me it is working as expected, and quite well.

**Comment by synfinatic** [comment]
Yeah, you're right, the behavior was changed in v1.16.0: https://github.com/synfinatic/aws-sso-cli/issues/696.

Anyways, have you read the docs I linked to?  Because it links to the answer you seek: https://synfinatic.github.io/aws-sso-cli/config/#configprofilesurlaction

**Comment by zonywhoop** [comment]
Yes - so I went back through the docs and had overlooked `ConfigProfilesUrlAction` - I set this to `open-url-in-container` and re-ran `config-profiles` and it does look like that is doing what I want.

However, this brought about another bug that I'm trying to get documentation together for around multiple SSO Profiles and `config-profiles` output.. I'll open another issue for that once I go back through the docs and make sure it's not just me missing something.
