### ISSUE TITLE
Warnings for missing access to accounts present in config

### ISSUE THREAD

**Issue by Moulick** [synfinatic/aws-sso-cli#980]
**Output of `aws-sso version`:**
```
Example output:
AWS SSO CLI Version 1.17.0 -- Copyright 2021-2024 Aaron Turner
Homebrew (1.17.0) built at 2024-07-10T21:26:18Z
```

**Describe the bug:**
Just updated to 1.17 and `aws-sso-cli` has started warning about missing access for accounts in the config file. My colleagues and I have a shared `aws-sso-cli` config file and not everyone has access to all the accounts in the config file. We were currently relying on the fact that `aws-sso-cli` does not give any error or warning if account access is missing and will only configure the ones that a person has access to. `aws-sso-cli` now has started warning which is annoying.

**To Reproduce:**
 1. Add some accounts to `~/.aws-sso/config.yaml` that you don't have access
 2. Run `aws-sso config-profiles` and see warning printed for missing access

**Expected behavior:**
Warning to not be printed if access is missing.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Version: 14.5 (23F79)

**Comment by synfinatic** [comment]
I can see about moving this to debug or something like that.  I'm curious though, what attributes are you providing in your shared config for these roles that makes it necessary to define them in the file?

**Comment by Moulick** [comment]
Moving to debug should pretty much solve this problem, I think. 

Main reason was for having a shared config are.
1. Standardizing the `ProfileFormat`, 
2. Providing `SSOConfig.Default.Accounts.Name` for some aws accounts where the actual aws name is stoopid and cannot be changed because _reasons_.
3. Different regions for different accounts. Make it easier to just run `export AWS_PROFILE=<xyz>` and the user get the right region for that account.
4. Add tags because why not, even though never really used.
5. Everyone gets the script for https://github.com/synfinatic/aws-sso-cli/issues/816
6. Quick onboarding for people with good defaults

**Comment by Moulick** [comment]
@synfinatic I see this is slated for the 2.0.0 release, is it possible to release this minor change as a patch version in v1.x.x series please? Or if the v2.0.0 release is close then nevermind :)

**Comment by synfinatic** [comment]
Beta5 should be out soonish. I honestly wouldn't recommend staying on head for long periods of time.
